### ISSUE TITLE
Sweep AI: Refactor avro>=1.10.2,<1.11 to be compatible with avro=1.11

### ISSUE THREAD

**Issue by wmaiouiru** [wmaiouiru/datahub#1]
In file: metadata-ingestion/setup.py and other files refactor avro>=1.10.2,<1.11 to be compatible with avro=1.11
In file: docker/datahub-ingestion-base/base-requirements.txt change default fastavro==1.7.4 to fastavro==1.8.2 

Context:
On fastavro==1.6.0, on MacOS M1 chip, I am getting the following error:
```
      Compiler crash traceback from this point on:
        File "/private/var/folders/yt/s_bgzcr54qb5ctt_n2gk_5lc0000gp/T/pip-build-env-j25_8sp7/overlay/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 2789, in call_self_node
          type_entry = self.type.args[0].type.entry
      AttributeError: 'PyObjectType' object has no attribute 'entry'
```
https://stackoverflow.com/questions/76835859/error-installing-fastavro-1-7-3-on-macos-python-3-10

In attempting to use fastavro==1.8.2, I am running into issues with hsfs[python]==3.2.1 be incompatible with acryl-datahub[datahub-rest,superset]==0.8.33.0

since:
avro==1.11.0 from hsfs[python]==3.2.1
avro<1.11,>=1.10.2 from acryl-datahub[datahub-rest,superset]==0.8.33.0

I would like to upgrade avro>=1.10.2,<1.11 to make the python packages compatible.

**Comment by wwzeng1** [comment]
sweep: retry

**Comment by wwzeng1** [comment]
sweep: retry

**Comment by wwzeng1** [comment]
sweep: retry

**Comment by kevinlu1248** [comment]
sweep: Retry
